### ISSUE TITLE
Unintentional redirect for hash value of "#{someString}"?

### ISSUE THREAD

**Issue by Khongchai** [wonderfulsoftware/webring#67]
Currently, a lot of people, when linking to this webring from their own sites are adhering to this pattern:

>>  https://somewebsite.com#somewebsite.com

Right now, for all sites that link to here using such patterns, the inbound handling will, instead of highlighting only the website specified after the hash value, also call the next() function and highlights the one after instead.

Examples using random websites from webring:

>> https://webring.wonderful.software#warat.win
>> https://webring.wonderful.software#llun.me
>> https://webring.wonderful.software#suam.wtf

Pick any from the example above and you will see that webring calls the next() function after half a second (you can also see that the next button is clicked), which is exactly what is written in your code ( index.js line 164 )

```js
if (inbound) {
          setTimeout(() => {
            next()
            autoNext.value = true
          }, 500)
        }
```

However, these (with slashes) are fine:

>> https://webring.wonderful.software/#/warat.win
>> https://webring.wonderful.software/#/llun.me
>> https://webring.wonderful.software/#/suam.wtf

The current implementation of hash handling inserts a slash in between the hash and its value. In such cases, matchLink would always be true, because the id provided is correct, it's just that the pattern is different.  Within the same loop, you return true ( index.js line 104)

```js
if (hash.startsWith("#") && !hash.startsWith("#/")) {
          const id = (
            (hash.match(/[a-z0-9\.-]+/i) || [])[0] || ""
          ).toLowerCase()
          location.replace("#/" + id)
          const matchedLink = links.find((l) => l.id === id)
          if (matchedLink) {
            sendBeacon("inbound", matchedLink.id)
            transitionInfo.needsInboundTransition = true
            inboundReferrer = matchedLink.id
            return true
          }
        }
      }
```

"true" would later be used in the if (inbound) line ( index.js line 157 )

```js
Vue.onMounted(() => {
        const inbound = processInboundLink()
        updateCurrentLink()
        if (!currentLink.value && location.hash !== "#/list") {
          autoRandom.value = true
          random()
        }
        if (inbound) {
          setTimeout(() => {
            next()
            autoNext.value = true
          }, 500)
        }

     // ...
```

So, the question is:

**Do you really need to check for**

```js

hash.startsWith("#")

```
in the if condition in line 104?  By removing it, the problem is solved immediately.

I believe this issue should be corrected asap as the pattern above is what is shown in the docs and as mentioned at the beginning, a lot of people are already using this pattern.

```js
//From docs here: https://github.com/wonderfulsoftware/webring
<a href="https://webring.wonderful.software#YOUR.DOMAIN" title="วงแหวนเว็บ">
  <img
    alt="วงแหวนเว็บ"
    width="32"
    height="32"
    src="https://webring.wonderful.software/webring.black.svg"
  />
</a>
```
I'm not making a pull request because I'm not sure whether this is intentional or not. The docs could just be wrong, and in that case, a simple edit, telling the people to prepend and append the hash with slashes would suffice.

```js
<a href="https://webring.wonderful.software/#/YOUR.DOMAIN" title="วงแหวนเว็บ">

//...

</a>
```

**Comment by dtinth** [comment]
@Khongchai Hi, thanks for raising an issue! This is intentional.

When they come to the webring through the webring icon, they are recommended to go to the next website in the ring. That’s why the next button is clicked automatically so they can enter the next site right away.

Maybe the UX is not that obvious… any suggestion is welcome!

**Comment by Khongchai** [comment]
Oh ok. I thought so too, but as you said, the UX made it seemed unintentional, even though the code is very explicit.

Is this feature really a necessity? Imagine people who don't yet realize what webring is, when they click on the logo it's already enough of a surprise to be taken to another site. When the browser finished loading webring, the users only have half a second to orient themselves and realize the connection between the previous site and webring before next() triggers. 

I think everybody who sees the list on webring would click around anyway so in my opinion, the feature is, though a very noble one, a tad confusing.

**Comment by dtinth** [comment]
@Khongchai 

> Oh ok. I thought so too, but as you said, the UX made it seemed unintentional, even though the code is very explicit.

I agree.

> Is this feature really a necessity? […] I think everybody who sees the list on webring would click around anyway

I [updated the statistics publishing script so that it publishes the number of navigations from one site to the next site](https://github.com/wonderfulsoftware/webring/commit/d7e90230522ec7385019dff2f29b6f9f073c753b).

The [stats are published here](https://github.com/wonderfulsoftware/webring-usage-stats/blob/main/traffic.json). As it turns out, much less people navigate to the next site directly than I expected. So as the data shows, I think your assumption is correct. Still, I want to encourage people to go to the next site in the ring as a primary action, so that it is, you know, a ring. But I agree the current UX is not going to make it.

Therefore I would very much welcome a PR to address this issue. Here are some ideas:

- Make the Next button slowly glow to highlight the next action.
- Make a YouTube-style autoplay (cancelable, circular countdown) that when the timer reaches zero, it takes the user to the next site in the ring.

These are just what I can think of, but feel free to do something else entirely if you prefer.

**Comment by Khongchai** [comment]
I like the first idea of drawing the user's attention to the next button. I'll talk to my UX designer about this idea, see if she has any comments.

**Comment by dtinth** [comment]
I have updated the UX to display a modal dialog like this:

![webring wonderful software_(iPhone SE)](https://user-images.githubusercontent.com/193136/155563268-2f2402d8-ac25-4533-9d11-6328db502747.png)

After clicking the button, the user is directed to the next site in the ring, as explained in the text. I will close this for now then.
